version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - VITE_API_URL=https://duomind.ru/api
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  postgres_data: 